apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
  labels:
    cluster: c0
    app: prometheus
spec:
  project: default
  source:
    repoURL: https://gihub.com/jakubbdevops/argocd.git
    targetRevision: HEAD
    path: prometheus
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
    - CreateNamespace=true
