apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directpv
  namespace: argocd
  labels:
    cluster: c0
    app: loki
spec:
  project: default
  source:
    repoURL: https://github.com/jakubbdevops/argocd.git
    targetRevision: HEAD
    path: apps/directpv
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true