apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-controler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.5.2
    helm:
      values: |
        controller:
          autoscaling:
            enabled: true
            minReplicas: 3
            maxReplicas: 8
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics